dist: bionic
language:  java
jdk: openjdk8

install: true
script: 
  - mvn install:install-file -Dfile=fake-repo/org/domainrobot/sdk-model/0.2.8/sdk-model-0.2.8.jar -DgroupId=org.domainrobot -DartifactId=sdk-model -Dversion=0.2.8 -Dpackaging=jar
  - mvn install:install-file -Dfile=fake-repo/org/domainrobot/sdk-client/0.2.8/sdk-client-0.2.8.jar -DgroupId=org.domainrobot -DartifactId=sdk-client -Dversion=0.2.8 -Dpackaging=jar
  - mvn clean verify
