## server settings
server:
  address: 127.0.0.1
  forward-headers-strategy: NATIVE
  port: 8081
  servlet:
    context-path: /
  shutdown: graceful

logging:
  level:
    web: debug

## credentials for the domainrobot sdk
autodns:
  context: 4
  password: pwd
  url: https://api.autodns.com/v1
  user: user

## enables the validation of the configured zones
zone:
  validation:
    enabled: true